Update: UX: Don't error just because unregistered projects
- It's likely a user will have unregistered projects. But
  that's not an error. The whole point is to audit those
  that are unregistered to see if there are any they care
  about.

  So don't print to stderr or exit nonzero because of
  unregistered projects. This is a reporting tool, and
  just reporting the truth is not an error.

  User is encouraged to use the weekly-omr-report cron
  job to help them monitor the OMR config. The cron job
  makes it easy to exempt unregistered projects from
  triggering an audit warning.

diff --git a/bin/omr-report b/bin/omr-report
--- a/bin/omr-report
+++ b/bin/omr-report
@@ -75,9 +75,12 @@ omr_report () {
   echo "Number of registered OMR projects: ${REG_CNT} (${SKP_CNT} skipped)"
 
   if [ ${UNK_CNT} -ne 0 ]; then
-    >&2 echo "ERROR: OMR missing this many gits: ${UNK_CNT}"
-
-    return 1
+    # But is it, though?
+    #
+    #  >&2 echo "ERROR: OMR missing this many gits: ${UNK_CNT}"
+    #
+    #  return 1
+    echo "- Number of unregistered projects: ${UNK_CNT}"
   fi
 }
 
