Update: UX: Tweak error messages

diff --git a/lib/checkout b/lib/checkout
--- a/lib/checkout
+++ b/lib/checkout
@@ -14,7 +14,7 @@
 [DEFAULT]
 checkout =
   if [ -z "${MR_REPO_REMOTES}" ]; then
-    >&2 echo "ERROR: Missing project-specific MR_REPO_REMOTES var, or 'checkout' action"
+    >&2 echo "ERROR: Please define either MR_REPO_REMOTES environ, or 'checkout' action"
     #
     exit 1
   fi
diff --git a/lib/wireRemotes b/lib/wireRemotes
--- a/lib/wireRemotes
+++ b/lib/wireRemotes
@@ -23,7 +23,7 @@
 wireRemotes =
   exit_if_arg_missing () {
     if [ -z "$1" ]; then
-      >&2 echo "ERROR: Incomplete MR_REPO_REMOTES for project: ${MR_REPO}"
+      >&2 echo "ERROR: Please set MR_REPO_REMOTES for project: ${MR_REPO}"
       #
       exit 1
     fi
